language: go
script: "./test.sh"
sudo: false
go:
    - 1.2.2
    - 1.3.3
    - 1.4.2
    - 1.5.1
    - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
after_success:
    - $HOME/gopath/bin/goveralls -service=travis-ci
